name: Deploy to AWS

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      # Install packages
      - name: Install packages
        run: npm install
      # Build project
      - name: Build project
        run: npm run build

      # Install Infra Packages
      - name: Install Infra Packages
        run: |
          cd infra/
          npm install

      # Configure AWS credentials
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIAWZRQKS3Y6JJBJIUX
          aws-secret-access-key: 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
          aws-region: us-east-1
      # Run cdk bootstrap
      - name: Run cdk bootstrap
        run: |
          cd infra/
          npm run cdk -- bootstrap
      # Run cdk
      - name: Run cdk
        run: |
          cd infra/
          npm run cdk -- deploy --all --require-approval never
